GET https://s585project-delivery.herokuapp.com/orders

###

GET https://s585project-delivery.herokuapp.com/orders/1

###

GET https://s585project-delivery.herokuapp.com/orders/search?delivererId=5&date1=2020-12-10 00:00:01&date2=2020-12-13 23:59:59

###

GET https://s585project-delivery.herokuapp.com/orders/customers/1

###

GET https://s585project-delivery.herokuapp.com/orders/vendors/1

###

DELETE https://s585project-delivery.herokuapp.com/orders/4/remove

###

GET https://s585project-delivery.herokuapp.com/carts/

###

GET https://s585project-delivery.herokuapp.com/carts/2/

###

POST https://s585project-delivery.herokuapp.com/carts
Content-Type: application/json

{
  "id": 0,
  "customerId": 2,
  "products": [
    1,
    2
  ],
  "qty": [
    2,
    3
  ]
}

###

POST https://s585project-delivery.herokuapp.com/carts/1/checkout

###

DELETE https://s585project-delivery.herokuapp.com/carts/4/remove

###

GET https://s585project-delivery.herokuapp.com/customers/

###

GET https://s585project-delivery.herokuapp.com/customers/2/

###

POST https://s585project-delivery.herokuapp.com/customers
Content-Type: application/json

{
  "id": 0,
  "name": "Громов",
  "address": "Казань, Тимирязева 4"
}

###

DELETE https://s585project-delivery.herokuapp.com/customers/6/remove

###

GET https://s585project-delivery.herokuapp.com/deliverers/

###

GET https://s585project-delivery.herokuapp.com/deliverers/2/

###

POST https://s585project-delivery.herokuapp.com/deliverers
Content-Type: application/json

{
  "id": 0,
  "name": "Полевой",
  "location": "Казань, Абсалямова 23"
}

###

DELETE https://s585project-delivery.herokuapp.com/deliverers/8/remove

###

GET https://s585project-delivery.herokuapp.com/vendors/

###

GET https://s585project-delivery.herokuapp.com/vendors/3

###

POST https://s585project-delivery.herokuapp.com/vendors
Content-Type: application/json

{
  "id": 0,
  "name": "Мясо в лаваше",
  "address": "Казань, Мусина 10А"
}

###

https://s585project-delivery.herokuapp.com/vendors/5/remove

###

GET https://s585project-delivery.herokuapp.com/products/

###

GET https://s585project-delivery.herokuapp.com/products/7

###

POST https://s585project-delivery.herokuapp.com/products/
Content-Type: application/json

{
  "id": 0,
  "categoryId": 1,
  "vendorId": 3,
  "name": "Шашлык",
  "unitPrice": 400
}

###

DELETE https://s585project-delivery.herokuapp.com/products/9/remove